# Generated by Django 4.2.14 on 2024-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=255)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='pblc_usr_signp_email_idx_0001')],
            },
        ),
    ]
